# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_steps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steps',
        ),
    ]
