# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=200, unique=True)),
                ('win', models.IntegerField(default=0)),
                ('loose', models.IntegerField(default=0)),
            ],
        ),
    ]
