# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xo', '0003_auto_20170331_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='player',
            field=models.CharField(default='', max_length=200),
        ),
    ]
